### ISSUE TITLE
Use IPFS 0.4.5

### ISSUE THREAD

**Issue by haadcode** [orbitdb/orbit#192]
This is issue is to track all the tasks related to using go-ipfs 0.4.5 in Orbit.

As of today, 0.4.5 is at pre1, meaning not even a release candidate yet, so things might break until 0.4.5 is officially released.

**Comment by haadcode** [comment]
What is needed for this goals to be completed:
- [ ] Orbit uses go-ipfs 0.4.5, bundled and brought in by ipfs/go-ipfs-dep
- [ ] Orbit uses pubsub from ipfs/js-ipfs-api
- [ ] All features work as before

**Comment by haadcode** [comment]
> Orbit uses go-ipfs 0.4.5, bundled and brought in by ipfs/go-ipfs-dep


Blocked by:
- using a fork @haad/go-ipfs-dep as an interim solution to pull in all the dependencies
- @haad/go-ipfs-dep refactoring PR needs to be updated (TODO: link)
- @haad/go-ipfs-dep refactoring PR needs to be merged to ipfs/go-ipfs-dep (TODO: link)
- go-ipfs 0.4.5 is pre1, ie. not released yet
- ipfs/go-ipfs-dep (version with 0.4.5) needs to be published to npm
- open bugs in go-ipfs 0.4.5 (eg. "too many open files bug", TODO: links)

> Orbit uses pubsub from ipfs/js-ipfs-api

Blocked by:
- using a fork @haad/js-ipfs-api which contains pubsub
- @haad/js-ipfs-api's pubsub tests need to be moved to interface-ipfs-core (TODO: link)
- @haad/js-ipfs-api pubsub and stream refactor PRs need to be created (TODO: link)
- @haad/js-ipfs-api pubsub and stream refactor PRs need to be merged to ipfs/js-ipfs-api (TODO: link)
- ipfs/js-ipfs-api (version with pubsub) needs to be published to npm

> All features work as before

Blocked by:
- File previews don't open anymore (regression from 0.4.5, need to investigate why, create an issue)
- "Error: socket hung up", related to the "too many open files" bug (TODO: links)
- "Already joined on'X'" error from pubsub after refreshing Electron (due to js-ipfs-api state not getting reset). Best possible fix here would return the existing subscription from pubsub instead of throwing an error, and handles state reset (this is tricky due to the stateless nature of js-ipfs-api)
- Swarm Peers view always shows 0 peers (TODO: link)

**Comment by haadcode** [comment]
With the latest merges, Orbit now uses go-ipfs 0.4.5-pre1. It's an early version and there are issues. Things may be broken leading up to the release of 0.4.5.

**Comment by haadcode** [comment]
That said, it's working :)

**Comment by aphelionz** [comment]
I believe this can be closed since we support both `js-ipfs` 0.36 and `go-ipfs` 0.4.22
