### ISSUE TITLE
Orbit browser version problems

### ISSUE THREAD

**Issue by haadcode** [orbitdb/orbit#210]
Report bugs with the browser version here.

**Comment by dignifiedquire** [comment]
Drag and drop fails:

<img width="1091" alt="screen shot 2016-12-13 at 19 26 02" src="https://cloud.githubusercontent.com/assets/790842/21153393/96f210de-c16a-11e6-9452-8a9ef6d567be.png">

No messages are being loaded:

<img width="1086" alt="screen shot 2016-12-13 at 19 28 03" src="https://cloud.githubusercontent.com/assets/790842/21153394/970bb372-c16a-11e6-9898-27a7d14c2408.png">

**Comment by haadcode** [comment]
<img width="766" alt="screen shot 2016-12-13 at 19 30 51" src="https://cloud.githubusercontent.com/assets/7499694/21153459/dedb5b4e-c16a-11e6-8f12-106e0aa9bae1.png">

<img width="771" alt="screen shot 2016-12-13 at 19 30 56" src="https://cloud.githubusercontent.com/assets/7499694/21153461/e179d7e0-c16a-11e6-83bd-545600f66845.png">

**Comment by haadcode** [comment]
One more new one:
<img width="765" alt="screen shot 2016-12-14 at 01 32 12" src="https://cloud.githubusercontent.com/assets/7499694/21165073/3e92bc76-c19d-11e6-9fff-d1a7cd56da79.png">

**Comment by dignifiedquire** [comment]
Reload is loosing the history. Even though I had a pretty long history, after a simple reload the history is empty (same channel,  same username). The loading indicator is running though.

**Comment by dignifiedquire** [comment]
![screen shot 2016-12-14 at 18 45 56](https://cloud.githubusercontent.com/assets/790842/21193742/921871e8-c22d-11e6-8331-1594ed637e3e.png)

**Comment by haadcode** [comment]
I'm also losing history on Firefox but not in chrome. @dignifiedquire can you try with both?

**Comment by dignifiedquire** [comment]
will try firefox later, but definitely seeing it in chrome

**Comment by dignifiedquire** [comment]
Floodsub error: https://github.com/libp2p/js-libp2p-floodsub/issues/11
<img width="1057" alt="screen shot 2016-12-14 at 16 22 07" src="https://cloud.githubusercontent.com/assets/790842/21198046/0bf9eb4e-c23e-11e6-99de-fd9cb8cf0e66.png">

**Comment by dignifiedquire** [comment]
There is a new build, with `master` + this bitswap branch: https://github.com/ipfs/js-ipfs-bitswap/tree/new which makes things really nice https://ipfs.io/ipfs/QmXi4w3S3DqcbESA28yYw63MWNhfs3oUK8b8FSfxjb6N1S 

Things are fast and stable even with > 5 peers now.

**Comment by haadcode** [comment]
Chrome doesn't play videos but throws an error related to "SourceBuffer". No idea why as this used to work and the code hasn't been touched. Could be a Chrome bug https://bugs.chromium.org/p/chromium/issues/detail?id=651904.

Firefox plays frags_bunny.mp4 still fine :)

**Comment by dignifiedquire** [comment]
This is the relevant PR https://github.com/ipfs/js-ipfs-bitswap/pull/83

**Comment by VictorBjelkholm** [comment]
Not sure if it's specific to the browser version of orbit but seemingly
.webm videos don't play in Orbit.

**Comment by dignifiedquire** [comment]
I tracked the history loading bug a bit more, and it seems that the ipfs-log is corrupted somehow. For example one state in https://github.com/haadcode/orbit-db-store/blob/master/src/Store.js#L56 for `merged` is

```json
```

**Comment by haadcode** [comment]
Most of these issues should now be fixed in master. Specifically the problems related to the messages loading are now fixed.

I'm going to close this one in order to have more granular issues for each specific bug in the future. Please open new issues as you come across bugs.

Thank you everyone for reporting the issues and participating in testing!
