### ISSUE TITLE
Orbit doesn't distinguish between days

### ISSUE THREAD

**Issue by diasdavid** [orbitdb/orbit#211]
<img width="527" alt="screen shot 2016-12-13 at 14 34 36" src="https://cloud.githubusercontent.com/assets/1211152/21162479/6319efde-c142-11e6-93e5-ed23e60fd899.png">

It is mixing messages from different days because the ordering is done by hour:min

**Comment by diasdavid** [comment]
consider also handling timezones

**Comment by theobat** [comment]
Links to #118

**Comment by theobat** [comment]
So I dived a little bit into this @haadcode and I don't understand why we have two different components for messages when so little seems to differ on the input side. Shall we use some kind of argument in the props if this is just a matter of size ?
We could simplify this :
```
      if (appSettings.useLargeMessage) {
        return <Message2
          message={message}
          key={message.hash}
          onReplyTo={this.onReplyTo.bind(this)}
          onShowProfile={this.onShowProfile.bind(this)}
          onDragEnter={this.onDragEnter.bind(this)}
          onScrollToPreview={this.onScrollToPreview.bind(this)}
          highlightWords={username}
          colorifyUsername={colorifyUsernames}
          useEmojis={useEmojis}
          style={{
            fontFamily: useMonospaceFont ? monospaceFont : font,
            fontSize: useMonospaceFont ? '0.9em' : '1.0em',
            fontWeight: useMonospaceFont ? '100' : '300',
            padding: spacing,
          }}
        />
      } else {
        return <Message
          message={message}
          key={message.hash}
          onReplyTo={this.onReplyTo.bind(this)}
          onShowProfile={this.onShowProfile.bind(this)}
          onDragEnter={this.onDragEnter.bind(this)}
          onScrollToPreview={this.onScrollToPreview.bind(this)}
          highlightWords={username}
          colorifyUsername={colorifyUsernames}
          useEmojis={useEmojis}
          style={{
            fontFamily: useMonospaceFont ? monospaceFont : font,
            fontSize: useMonospaceFont ? '0.9em' : '1.0em',
            fontWeight: useMonospaceFont ? '100' : '300',
            padding: spacing,
          }}
        />
      }
```

**Comment by haadcode** [comment]
@theobat Yes, absolutely, this part could be refactored to much simpler. I would not put the size as a flag but wrap it in higher order components that handle only the layout. 

I've been prototyping to re-write all of the channel components, something like this: https://codepen.io/anon/pen/PbBryY?editors=0010 (code https://gist.github.com/haadcode/b038ce6be019e0ef841258c168b3bd53). You can play with the Pen by changing the largeMessages and feedMessages booleans (at the bottom) to change the layout. The actual decision between large/small happens here: https://gist.github.com/haadcode/b038ce6be019e0ef841258c168b3bd53#file-components-js-L236.

Hope that gives an idea how this could be refactored.

**Comment by haadcode** [comment]
Working on this and tracking the work in the original issue. Closing in favor of https://github.com/orbitdb/orbit/issues/118.
