### ISSUE TITLE
Orbit organization

### ISSUE THREAD

**Issue by diasdavid** [orbitdb/orbit#219]
Creating and subscribing to this issue, so that I get notified when Orbit becomes its on Github org :)

**Comment by haadcode** [comment]
https://github.com/orbit is taken :/

Not sure what would be a good alternative...

**Comment by VictorBjelkholm** [comment]
Brainstorming some names related to orbit:
* apogee
* perigee
* trajectory

Orbit in Spanish might work, `orbita`.
Or maybe Finnish: `kiertorata`

**Comment by wking** [comment]
Mmm [peerogi](https://en.wikipedia.org/wiki/Pierogi).  Probably too far from space though :p.

**Comment by diasdavid** [comment]
We got https://github.com/orbitdb \o/

**Comment by jbenet** [comment]
What's holding this back? I need this to happen soon, as I need to refer people to the group of orbit repos.

**Comment by RichardLitt** [comment]
It hadn't clearly been prioritized for anyone. I'll work on this this week, and ask @haadcode to move over repos when he's back from vacation.

**Comment by RichardLitt** [comment]
Started. https://github.com/orbitdb/orbitdb. See https://github.com/orbitdb/orbitdb/issues/1 for a discussion on which repos to move there. I can shape things up better as I know more.

**Comment by haadcode** [comment]
> I need this to happen soon, as I need to refer people to the group of orbit repos.

@jbenet can you elaborate here on the urgency and target? Is there an event coming at a specific date where we want to talk about orbit(db)? What exactly is "people" in this case, a particular set of users or generally?

**Comment by diasdavid** [comment]
I believe it is because as orbit get's linked, it is easier to attract people to 'orbit the endeavor', than 'orbit the app'. Plus it is a discoverability thing, in the same way we tell people to go to github.com/ipfs for IPFS things, github.com/orbitdb for orbit things.

**Comment by haadcode** [comment]
Here we go: https://github.com/orbitdb/orbit. 👋

**Comment by haadcode** [comment]
Considering this goal completed. Rest of the orbit related repos still moving and tracked in https://github.com/orbitdb/orbitdb/issues/1.
