### ISSUE TITLE
Reorganize this code base

### ISSUE THREAD

**Issue by haadcode** [orbitdb/orbit#223]
We need to separate the UI from the electron app so that we have stand-alone repos for the web version and electron version.

Originally discussed here: https://github.com/haadcode/orbit/issues/112 and https://github.com/haadcode/orbit/issues/220#issuecomment-271596527.

WIP repos:
- https://github.com/orbitdb/orbit-electron
- https://github.com/orbitdb/orbit-web

Part of bigger reorganization of all orbit related repos: https://github.com/orbitdb/orbitdb/issues/1.

What needs to be done here is to move the code in `client/` to `orbit-web` repo and `./` to `orbit-electron`.

**Comment by haadcode** [comment]
Most of the work has been now completed. Mentioned in https://github.com/haadcode/orbit/issues/112. The following repos have been created to split the code in this repo:

- [orbit-core](https://github.com/orbitdb/orbit-core) - Core Orbit library
- [orbit-web](https://github.com/orbitdb/orbit-web) - Orbit browser app
- [orbit-electron](https://github.com/orbitdb/orbit-electron) - Orbit desktop app

**Comment by haadcode** [comment]
Added also note to the README that says we're in the process of reorganizing everything and that the code will disappear from here soon.

**Comment by haadcode** [comment]
What still needs to be done is to actually transfer haadcode/orbit to orbitdb/orbit. I will do so today I hope. And we need to keep updating the README of orbitdb/orbit as we go, many links have been broken.

**Comment by dignifiedquire** [comment]
@haadcode got some issues with the latest version on https://ipfs.io/ipfs/QmRBmZDB1ssGCchXx1aKM7smiAghRDLKwYR5dWGrozxXCJ/#/channel/ipfs

- peers count is always zero
- getting actual messages takes a loong time
- error in the console: 
![screen shot 2017-02-06 at 18 34 11](https://cloud.githubusercontent.com/assets/790842/22658832/bfe9e186-ec9b-11e6-89f8-fa0736451eac.png)

**Comment by haadcode** [comment]
This code base has now been reorganized and transferred to https://github.com/orbitdb/orbit. Take good care!

**Comment by haadcode** [comment]
@dignifiedquire the 0 peers issue has been logged, the error should be gone now, for the third one, don't know why getting messages take a long time. We'll need to investigate.
