### ISSUE TITLE
Orbit should be usable at https://orbit.chat

### ISSUE THREAD

**Issue by haadcode** [orbitdb/orbit#225]
We want to make Orbit available at a nice url with minimal setup and installation to user. The ideal UX here is that user opens https://orbit.chat in their browser and will be able to use Orbit. That's it.

What needs to be done here is to figure out:
- orbit-web release process
- how we can deploy new version to https://orbit.chat

**Comment by haadcode** [comment]
@lgierth just to verify, we have orbit.chat domain, right?

**Comment by VictorBjelkholm** [comment]
@haadcode I can confirm that there is a orbit.chat.

**Comment by lgierth** [comment]
yep we have orbit.chat

**Comment by RichardLitt** [comment]
@lgierth What do we need to do to get it up at orbit.chat? Is the process to go through https://github.com/ipfs/ops-requests?

**Comment by VictorBjelkholm** [comment]
@RichardLitt I think, as long as you can hand over a multihash with the application running, we can pin & deploy it on the domain.

**Comment by diasdavid** [comment]
At some point in the last couple of months, I had a chat with @haadcode and we found that having web.orbit.chat to be the hosted web version and orbit.chat to be the entry point where people can find about orbit and download the executables too :)

**Comment by haadcode** [comment]
> having web.orbit.chat to be the hosted web version and orbit.chat to be the entry point where people can find about orbit and download the executables too

Correct. However, as we don't have a website for orbit, yet, and building a separate (from dist.ipfs.io) download page, I think the best way forward here is to start with orbit (the web app) being at orbit.chat. There's a task to add a banner "You can also use Orbit as a Desktop app, download here" to the app that points to dist.ipfs.io, which should be trivial. Over time, as we build a proper website for Orbit, we can move the app to web.orbit.chat and have the website at orbit.chat.

@VictorBjelkholm is there a way to have this process so that I could deploy it myself to the domain? Who, at the moment, is able to deploy it to the domain? I'm trying to make sure that we don't have a bottleneck between dev and ops and can quickly deploy new versions as needed.

**Comment by haadcode** [comment]
@RichardLitt orbit-web build process has now been documented, see here https://github.com/orbitdb/orbit-web#distribution-package. That should be all you need from orbit's side to progress with this. Following the instructions, you'll get a folder `dist/` (and its multihash) which can be deployed on a web server or as a stand-alone local app. It contains index.html and all the assets orbit-web needs to run.

**Comment by haadcode** [comment]
@RichardLitt small request: when you start working on this again actively, can you move the card in https://waffle.io/haadcode/orbit to "In Progress"?

**Comment by RichardLitt** [comment]
I've added a command to automatically add the hash to ops-requests. A bit overkill, but now it's automated. https://github.com/orbitdb/orbit-web/pull/1

**Comment by RichardLitt** [comment]
@haadcode I think this can be closed? Is this done now?

**Comment by haadcode** [comment]
I'll review this today and check the workflow and tools. Will let you know 👍

**Comment by lgierth** [comment]
now with ssl: https://orbit.chat

**Comment by lgierth** [comment]
and ipv6

**Comment by haadcode** [comment]
This has been completed now. We have been deploying latest version of orbit-web to orbit.chat for a while now. With the latest merges to master, we now have the deployment process documented at https://github.com/orbitdb/orbit-web#publish.

Thank you everyone for making this happen, it's been a long road since last summer but we now have https://orbit.chat working and integrated into our workflow! 😄 🏅 ❤️ 🎉
