### ISSUE TITLE
Orbit makes firefox crash

### ISSUE THREAD

**Issue by DeveloppSoft** [orbitdb/orbit#234]
Hi we tried orbit.chat with a few friends and after some use in firefox in makes firefox crash (or make the whole system lag).

**Comment by haadcode** [comment]
Thanks for reporting the issue @DeveloppSoft! This is a known issue and being figured out in https://github.com/orbitdb/orbit-web/issues/9, https://github.com/ipfs/js-ipfs/issues/950 and https://github.com/orbitdb/orbit-web/issues/8. 

Will update this issue when there's a fix.
