### ISSUE TITLE
Not loading over unsecure connection

### ISSUE THREAD

**Issue by layderv** [orbitdb/orbit#235]
http://orbit.chat does not work, while https://orbit.chat works properly as expected.
The former remains stuck at "LOADING".

**Comment by wildyeast** [comment]
Can reproduce in Chromium 62: When I use insecure http, I get [this error exactly](https://github.com/orbitdb/orbit-web/issues/9#issuecomment-323520295). In Firefox 56 the app runs fine with either secure or insecure http.

**Comment by aphelionz** [comment]
I believe this is a "feature" of WebCrypto currently. Falling back to an HTTP-safe crypto lib is in discussion, but extremely non-trivial. Closing for now with the workaround being HTTPS
