### ISSUE TITLE
Configurable server and webrtc-star URIs

### ISSUE THREAD

**Issue by lgierth** [orbitdb/orbit#34]
We need to be able to set them to `https://webrtc.orbit.ipfs.io` and `https://pubsub.orbit.ipfs.io` (or anything really).

This needs to happen very soon so we can e.g. run orbit on https://orbit.ipfs.io.

**Comment by haadcode** [comment]
This will become available as part of ipfs-daemon: https://github.com/haadcode/ipfs-daemon#new-ipfsdaemonoptions.

There's some work required on the UI side but it'll be available in a configuration screen after https://github.com/haadcode/orbit/pull/184 has been merged.

**Comment by haadcode** [comment]
This has been implemented now in Orbit. You can set it in the browser version at login screen / configuration.

Where are we with the https support @lgierth and @diasdavid?

@lgierth Wanna change the issue title to be specific about support for https or close this and open a new one to track the https support as its own goal? Either is fine by me, feel free to decide.

**Comment by diasdavid** [comment]
@lgierth if we get dns support in multiaddr, we can bypass https because then I can use https://github.com/diasdavid/webrtc-connect instead of websockets :)

**Comment by haadcode** [comment]
This should now be solved completely. orbit-web is now using `star-signal.cloud.ipfs.team` as the signalling server address. You can verify/change it in the configuration screen (bottom-right corner in the login screen).
